/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as testsTestErrorRouteImport } from './routes/(tests)/test-error'
import { Route as testsTest404RouteImport } from './routes/(tests)/test-404'
import { Route as pagesWaitlistRouteImport } from './routes/(pages)/waitlist'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as pagesAboutRouteImport } from './routes/(pages)/about'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiNewsletterUnsubscribeRouteImport } from './routes/api/newsletter/unsubscribe'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as ApiNewsletterStatusRouteImport } from './routes/api/newsletter/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const testsTestErrorRoute = testsTestErrorRouteImport.update({
  id: '/(tests)/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTest404Route = testsTest404RouteImport.update({
  id: '/(tests)/test-404',
  path: '/test-404',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesWaitlistRoute = pagesWaitlistRouteImport.update({
  id: '/(pages)/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAboutRoute = pagesAboutRouteImport.update({
  id: '/(pages)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterUnsubscribeRoute =
  ApiNewsletterUnsubscribeRouteImport.update({
    id: '/api/newsletter/unsubscribe',
    path: '/api/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterStatusRoute = ApiNewsletterStatusRouteImport.update({
  id: '/api/newsletter/status',
  path: '/api/newsletter/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/contact': typeof pagesContactRoute
  '/waitlist': typeof pagesWaitlistRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/contact': typeof ApiContactRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/newsletter/status': typeof ApiNewsletterStatusRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/contact': typeof pagesContactRoute
  '/waitlist': typeof pagesWaitlistRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/contact': typeof ApiContactRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/newsletter/status': typeof ApiNewsletterStatusRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/about': typeof pagesAboutRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/waitlist': typeof pagesWaitlistRoute
  '/(tests)/test-404': typeof testsTest404Route
  '/(tests)/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/contact': typeof ApiContactRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/newsletter/status': typeof ApiNewsletterStatusRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/newsletter/unsubscribe': typeof ApiNewsletterUnsubscribeRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/contact'
    | '/waitlist'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/contact'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/settings/apikeys'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/newsletter/status'
    | '/api/newsletter/subscribe'
    | '/api/newsletter/unsubscribe'
    | '/api/storage/file'
    | '/api/storage/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manifest.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/contact'
    | '/waitlist'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/contact'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/settings/apikeys'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/settings'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/newsletter/status'
    | '/api/newsletter/subscribe'
    | '/api/newsletter/unsubscribe'
    | '/api/storage/file'
    | '/api/storage/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/about'
    | '/(pages)/contact'
    | '/(pages)/waitlist'
    | '/(tests)/test-404'
    | '/(tests)/test-error'
    | '/admin/users'
    | '/api/contact'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/settings/apikeys'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/settings/'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/newsletter/status'
    | '/api/newsletter/subscribe'
    | '/api/newsletter/unsubscribe'
    | '/api/storage/file'
    | '/api/storage/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAboutRoute: typeof pagesAboutRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesWaitlistRoute: typeof pagesWaitlistRoute
  testsTest404Route: typeof testsTest404Route
  testsTestErrorRoute: typeof testsTestErrorRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNewsletterStatusRoute: typeof ApiNewsletterStatusRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
  ApiNewsletterUnsubscribeRoute: typeof ApiNewsletterUnsubscribeRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(tests)/test-error': {
      id: '/(tests)/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof testsTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-404': {
      id: '/(tests)/test-404'
      path: '/test-404'
      fullPath: '/test-404'
      preLoaderRoute: typeof testsTest404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/waitlist': {
      id: '/(pages)/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof pagesWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/about': {
      id: '/(pages)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof pagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/unsubscribe': {
      id: '/api/newsletter/unsubscribe'
      path: '/api/newsletter/unsubscribe'
      fullPath: '/api/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/status': {
      id: '/api/newsletter/status'
      path: '/api/newsletter/status'
      fullPath: '/api/newsletter/status'
      preLoaderRoute: typeof ApiNewsletterStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAboutRoute: pagesAboutRoute,
  pagesContactRoute: pagesContactRoute,
  pagesWaitlistRoute: pagesWaitlistRoute,
  testsTest404Route: testsTest404Route,
  testsTestErrorRoute: testsTestErrorRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNewsletterStatusRoute: ApiNewsletterStatusRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
  ApiNewsletterUnsubscribeRoute: ApiNewsletterUnsubscribeRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
